; LLVM IR generated by lang compiler
target triple = "x86_64-unknown-linux-gnu"

define i64 @main() {
entry:
    %sum = alloca i64
    store i64 0, i64* %sum
    %i = alloca i64
    store i64 0, i64* %i
    br label %L0
L0:
    %t0 = load i64, i64* %i
    %t2 = icmp slt i64 %t0, 10
    %t1 = zext i1 %t2 to i64
    %t3 = icmp ne i64 %t1, 0
    br i1 %t3, label %L1, label %L2
L1:
    %j = alloca i64
    store i64 0, i64* %j
    br label %L3
L3:
    %t4 = load i64, i64* %j
    %t6 = icmp slt i64 %t4, 5
    %t5 = zext i1 %t6 to i64
    %t7 = icmp ne i64 %t5, 0
    br i1 %t7, label %L4, label %L5
L4:
    %t8 = load i64, i64* %sum
    %t9 = add i64 %t8, 1
    store i64 %t9, i64* %sum
    %t10 = load i64, i64* %j
    %t11 = add i64 %t10, 1
    store i64 %t11, i64* %j
    br label %L3
L5:
    br label %L2
    %t12 = load i64, i64* %i
    %t13 = add i64 %t12, 1
    store i64 %t13, i64* %i
L2:
    %t14 = load i64, i64* %sum
    ret i64 %t14
}

