.PHONY: all init bootstrap bootstrap-local bootstrap-verify build release test test-suite test-all test-compiler-wasm test-direct-wasm test-run clean distclean \
		build-kernel build-lang-reader emit-kernel-ast emit-lang-reader-ast emit-compiler-ast \
		seed-bootstrap test-composition test-bootstrap generate-os-layer generate-version-info llvm-verify \
		compile run stdlib-run dev-run dev-stdlib-run status

# Get git info
GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_DIRTY := $(shell test -z "$$(git status --porcelain 2>/dev/null)" || echo "-dirty")
VERSION := $(GIT_COMMIT)$(GIT_DIRTY)
BOOTSTRAP_FROM := $(shell cat bootstrap/current/COMMIT 2>/dev/null || echo "unknown")

# The canonical bootstrap archives the previous root of trust on GitHub.
# bootstrap-local runs the identical pipeline with only that external upload
# disabled; all local verification, archival, promotion, and installation stay.
PUBLISH_BOOTSTRAP ?= 1

# OS detection
UNAME := $(shell uname -s)
ifeq ($(UNAME),Darwin)
    PLATFORM := macos
else
    PLATFORM := linux
endif

# Target selection (environment variables)
# LANGOS: auto-detected from platform
# LANGBE: backend override; built compilers default to their baked-in backend
# LANGLIBC: none (default, use raw syscalls), libc (use system libc)
LANGOS ?= $(PLATFORM)
LANGBE ?= x86
LANGLIBC ?= none

# OS layer file selection
# macOS MUST use libc (macos_arm64.lang uses hex literals which lexer doesn't support)
# Linux can use raw syscalls
ifeq ($(LANGOS),macos)
    OS_LAYER := std/os/libc_macos.lang
else ifeq ($(LANGLIBC),libc)
    OS_LAYER := std/os/libc.lang
else ifeq ($(LANGOS),linux)
    OS_LAYER := std/os/linux_x86_64.lang
else
    $(error Unknown LANGOS: $(LANGOS). Valid values: linux, macos)
endif

# Bootstrap: LLVM IR is primary (cross-platform), x86 is secondary (Linux fast path)
ifeq ($(PLATFORM),macos)
    BOOTSTRAP_LL := bootstrap/current/compiler_macos.ll
    BOOTSTRAP_LIBC := std/os/libc_macos.lang
else
    BOOTSTRAP_LL := bootstrap/current/compiler_linux.ll
    BOOTSTRAP_LIBC := std/os/libc.lang
endif
# Compiler paths
LANG := out/lang
LANG_NEXT := out/lang_next

# gh CLI for the bootstrap archive step: strip any env GITHUB_TOKEN/GH_TOKEN so
# gh uses the authenticated keyring account. Exported automation tokens may have
# narrower repository permissions than the interactive account.
GH := env -u GITHUB_TOKEN -u GH_TOKEN gh

# Default target
all: build

# Generate std/os.lang based on LANGOS
generate-os-layer:
	@echo 'include "$(OS_LAYER)"' > std/os.lang

# Generate out/version_info.lang with build-time constants
# Architecture detection
ARCH := $(shell uname -m)
ifeq ($(ARCH),arm64)
    BUILD_ARCH := arm64
else ifeq ($(ARCH),aarch64)
    BUILD_ARCH := arm64
else
    BUILD_ARCH := x86_64
endif

# Infer libc mode: macOS always uses libc, Linux uses OS_LAYER
ifeq ($(LANGOS),macos)
    EFFECTIVE_LIBC := system
else ifeq ($(findstring libc,$(OS_LAYER)),libc)
    EFFECTIVE_LIBC := system
else
    EFFECTIVE_LIBC := none
endif

generate-version-info:
	@mkdir -p out
	@BOOTSTRAP_FROM="$(BOOTSTRAP_FROM)"; \
	echo '// Auto-generated by Makefile - do not edit manually' > out/version_info.lang; \
	echo 'var LANG_VERSION *u8 = "0.1.0";' >> out/version_info.lang; \
	echo 'var LANG_COMMIT *u8 = "$(VERSION)";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_BACKEND *u8 = "$(LANGBE)";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_OS *u8 = "$(LANGOS)";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_ARCH *u8 = "$(BUILD_ARCH)";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_LIBC *u8 = "$(EFFECTIVE_LIBC)";' >> out/version_info.lang; \
	echo "var LANG_BOOTSTRAP_FROM *u8 = \"$$BOOTSTRAP_FROM\";" >> out/version_info.lang

# Init: build from bootstrap LLVM IR (cross-platform)
init:
	@mkdir -p out
	@echo "Initializing from $(BOOTSTRAP_LL)..."
	clang -O2 $(BOOTSTRAP_LL) -o out/lang_bootstrap
	ln -sf lang_bootstrap $(LANG)
	@echo "Created: $(LANG) -> lang_bootstrap"

# Build: compile src/*.lang with the stable compiler -> lang_next.
# LLVM/libc is the primary development path on both supported platforms.
build:
	@$(MAKE) generate-os-layer generate-version-info LANGBE=llvm LANGOS=$(PLATFORM) LANGLIBC=libc
	@if [ ! -f $(LANG) ] && [ ! -L $(LANG) ]; then \
		$(MAKE) init; \
	fi
	@mkdir -p out
	LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) std/core.lang out/version_info.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o out/lang_dev_$(VERSION).ll
	clang -O2 out/lang_dev_$(VERSION).ll -o out/lang_dev_$(VERSION)
	ln -sf lang_dev_$(VERSION) $(LANG_NEXT)
	@echo "Created: $(LANG_NEXT) -> lang_dev_$(VERSION)"

# ============================================================
# BOOTSTRAP: The ONE command to verify and promote
# ============================================================
# LLVM-FIRST: All verification uses LLVM IR (cross-platform).
# x86 assembly is only emitted as optional artifact on Linux.
#
# Verification chain:
#   Stage 1: Root of trust (ctrusted from LLVM bootstrap)
#   Stage 2: Generation 1 (kernel1 built by trusted, LLVM output)
#   Stage 3: Generation 2 + LLVM fixed point check
#   Stage 4: AST fixed point check
#   Stage 5: Generate and cross-check both platform roots
#   Stage 6: Validate the exact native binary to be promoted
#   Stage 7: Archive the old root, then promote and install
#
# Run this ONE command. Nothing else. No shortcuts.
bootstrap:
	@mkdir -p out
	@# Generate version info with LLVM backend (bootstrap always uses LLVM)
	@BOOTSTRAP_FROM="$(BOOTSTRAP_FROM)"; \
	echo '// Auto-generated by Makefile - do not edit manually' > out/version_info.lang; \
	echo 'var LANG_VERSION *u8 = "0.1.0";' >> out/version_info.lang; \
	echo 'var LANG_COMMIT *u8 = "$(VERSION)";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_BACKEND *u8 = "llvm";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_OS *u8 = "$(PLATFORM)";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_ARCH *u8 = "$(BUILD_ARCH)";' >> out/version_info.lang; \
	echo 'var LANG_BUILD_LIBC *u8 = "system";' >> out/version_info.lang; \
	echo "var LANG_BOOTSTRAP_FROM *u8 = \"$$BOOTSTRAP_FROM\";" >> out/version_info.lang
	@echo "╔════════════════════════════════════════════════════════════════╗"
	@echo "║           BOOTSTRAP: VERIFY + PROMOTE (LLVM-FIRST)             ║"
	@echo "╚════════════════════════════════════════════════════════════════╝"
	@echo ""
	@# Never trust leftovers from a failed or interrupted prior bootstrap.
	@rm -rf /tmp/bootstrap_verify
	@mkdir -p out out/ast /tmp/bootstrap_verify
	@command -v clang >/dev/null || { echo "ERROR: clang is required"; exit 1; }
	@if [ "$(PUBLISH_BOOTSTRAP)" = "1" ]; then \
		command -v gh >/dev/null || { echo "ERROR: gh is required for bootstrap archive releases"; exit 1; }; \
		$(GH) auth status >/dev/null 2>&1 || { echo "ERROR: gh is not authenticated"; exit 1; }; \
	fi
	@echo "┌────────────────────────────────────────────────────────────────┐"
	@echo "│ STAGE 1: ROOT OF TRUST                                         │"
	@echo "└────────────────────────────────────────────────────────────────┘"
	@echo "Platform: $(PLATFORM)"
	@echo "Bootstrap: $(BOOTSTRAP_LL)"
	@if [ ! -f $(BOOTSTRAP_LL) ]; then echo "ERROR: $(BOOTSTRAP_LL) not found"; exit 1; fi
	clang -O2 $(BOOTSTRAP_LL) -o /tmp/bootstrap_verify/ctrusted
	@echo "Built: ctrusted from $(BOOTSTRAP_LL)"
	@echo ""
	@echo "┌────────────────────────────────────────────────────────────────┐"
	@echo "│ STAGE 2: GENERATION 1 (Built by Trusted)                       │"
	@echo "└────────────────────────────────────────────────────────────────┘"
	@# Set up OS layer for LLVM compilation
	@echo 'include "$(BOOTSTRAP_LIBC)"' > std/os.lang
	@# Build kernel1 using LLVM backend
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/bootstrap_verify/ctrusted std/core.lang out/version_info.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/kernel1.ll
	clang -O2 /tmp/bootstrap_verify/kernel1.ll -o /tmp/bootstrap_verify/kernel1
	@echo "Built: kernel1 (LLVM)"
	@# Emit reader AST 1 using kernel1
	/tmp/bootstrap_verify/kernel1 src/lang_reader.lang --emit-expanded-ast -o /tmp/bootstrap_verify/reader_ast1.ast
	@echo "Emitted: reader_ast1.ast ($$(wc -l < /tmp/bootstrap_verify/reader_ast1.ast) lines)"
	@echo ""
	@echo "┌────────────────────────────────────────────────────────────────┐"
	@echo "│ STAGE 3: GENERATION 2 + 3 (LLVM FIXED POINT)                   │"
	@echo "└────────────────────────────────────────────────────────────────┘"
	@# Build kernel2 (kernel1 compiles sources)
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/bootstrap_verify/kernel1 std/core.lang out/version_info.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/kernel2.ll
	clang -O2 /tmp/bootstrap_verify/kernel2.ll -o /tmp/bootstrap_verify/kernel2
	@echo "Built: kernel2 (LLVM)"
	@# Build kernel3 (kernel2 compiles sources) for true fixed point
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/bootstrap_verify/kernel2 std/core.lang out/version_info.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/kernel3.ll
	@echo ""
	@echo "Checking LLVM FIXED POINT (kernel2.ll === kernel3.ll)..."
	@if diff -q /tmp/bootstrap_verify/kernel2.ll /tmp/bootstrap_verify/kernel3.ll > /dev/null; then \
		echo "✓ LLVM FIXED POINT VERIFIED"; \
	else \
		echo ""; \
		echo "!!! LLVM FIXED POINT FAILED !!!"; \
		echo "kernel2.ll and kernel3.ll differ:"; \
		diff /tmp/bootstrap_verify/kernel2.ll /tmp/bootstrap_verify/kernel3.ll | head -20; \
		exit 1; \
	fi
	@echo ""
	@echo "┌────────────────────────────────────────────────────────────────┐"
	@echo "│ STAGE 4: AST FIXED POINT                                       │"
	@echo "└────────────────────────────────────────────────────────────────┘"
	@# Emit reader AST 2 using kernel2
	/tmp/bootstrap_verify/kernel2 src/lang_reader.lang --emit-expanded-ast -o /tmp/bootstrap_verify/reader_ast2.ast
	@echo ""
	@echo "Checking AST FIXED POINT (reader_ast1 === reader_ast2)..."
	@if diff -q /tmp/bootstrap_verify/reader_ast1.ast /tmp/bootstrap_verify/reader_ast2.ast > /dev/null; then \
		echo "✓ AST FIXED POINT VERIFIED"; \
	else \
		echo ""; \
		echo "!!! AST FIXED POINT FAILED !!!"; \
		echo "reader_ast1.ast and reader_ast2.ast differ:"; \
		diff /tmp/bootstrap_verify/reader_ast1.ast /tmp/bootstrap_verify/reader_ast2.ast | head -20; \
		exit 1; \
	fi
	@echo ""
	@echo "┌────────────────────────────────────────────────────────────────┐"
	@echo "│ STAGE 5: GENERATE BOOTSTRAP FILES                              │"
	@echo "└────────────────────────────────────────────────────────────────┘"
	@# Generate bootstrap files for both platforms using kernel2
	@echo "Generating cross-platform bootstrap files..."
	@# Linux LLVM bootstrap
	@echo 'include "std/os/libc.lang"' > std/os.lang
	@echo '// Auto-generated by Makefile - do not edit manually' > /tmp/bootstrap_verify/version_info_linux.lang
	@echo 'var LANG_VERSION *u8 = "0.1.0";' >> /tmp/bootstrap_verify/version_info_linux.lang
	@echo 'var LANG_COMMIT *u8 = "$(VERSION)";' >> /tmp/bootstrap_verify/version_info_linux.lang
	@echo 'var LANG_BUILD_BACKEND *u8 = "llvm";' >> /tmp/bootstrap_verify/version_info_linux.lang
	@echo 'var LANG_BUILD_OS *u8 = "linux";' >> /tmp/bootstrap_verify/version_info_linux.lang
	@echo 'var LANG_BUILD_ARCH *u8 = "x86_64";' >> /tmp/bootstrap_verify/version_info_linux.lang
	@echo 'var LANG_BUILD_LIBC *u8 = "system";' >> /tmp/bootstrap_verify/version_info_linux.lang
	@echo 'var LANG_BOOTSTRAP_FROM *u8 = "$(BOOTSTRAP_FROM)";' >> /tmp/bootstrap_verify/version_info_linux.lang
	LANGBE=llvm LANGOS=linux /tmp/bootstrap_verify/kernel2 std/core.lang /tmp/bootstrap_verify/version_info_linux.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/compiler_linux.ll
	@echo "Cross-checking compiler_linux.ll as x86_64 Linux object..."
	clang -O2 -c -target x86_64-unknown-linux-gnu /tmp/bootstrap_verify/compiler_linux.ll -o /tmp/bootstrap_verify/compiler_linux.o || { echo "ERROR: compiler_linux.ll failed cross-target verification"; exit 1; }
	@echo "✓ compiler_linux.ll cross-target verified"
	@# macOS LLVM bootstrap
	@echo 'include "std/os/libc_macos.lang"' > std/os.lang
	@echo '// Auto-generated by Makefile - do not edit manually' > /tmp/bootstrap_verify/version_info_macos.lang
	@echo 'var LANG_VERSION *u8 = "0.1.0";' >> /tmp/bootstrap_verify/version_info_macos.lang
	@echo 'var LANG_COMMIT *u8 = "$(VERSION)";' >> /tmp/bootstrap_verify/version_info_macos.lang
	@echo 'var LANG_BUILD_BACKEND *u8 = "llvm";' >> /tmp/bootstrap_verify/version_info_macos.lang
	@echo 'var LANG_BUILD_OS *u8 = "macos";' >> /tmp/bootstrap_verify/version_info_macos.lang
	@echo 'var LANG_BUILD_ARCH *u8 = "arm64";' >> /tmp/bootstrap_verify/version_info_macos.lang
	@echo 'var LANG_BUILD_LIBC *u8 = "system";' >> /tmp/bootstrap_verify/version_info_macos.lang
	@echo 'var LANG_BOOTSTRAP_FROM *u8 = "$(BOOTSTRAP_FROM)";' >> /tmp/bootstrap_verify/version_info_macos.lang
	LANGBE=llvm LANGOS=macos /tmp/bootstrap_verify/kernel2 std/core.lang /tmp/bootstrap_verify/version_info_macos.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/compiler_macos.ll
	@echo "Cross-checking compiler_macos.ll as arm64 macOS object..."
	clang -O2 -c -target arm64-apple-macosx /tmp/bootstrap_verify/compiler_macos.ll -o /tmp/bootstrap_verify/compiler_macos.o || { echo "ERROR: compiler_macos.ll failed cross-target verification"; exit 1; }
	@echo "✓ compiler_macos.ll cross-target verified"
	@# Build the native binary that Stage 6 will actually execute.
	clang -O2 /tmp/bootstrap_verify/compiler_$(PLATFORM).ll -o /tmp/bootstrap_verify/compiler_$(PLATFORM) || { echo "ERROR: native compiler_$(PLATFORM) failed to link"; exit 1; }
	@echo "✓ compiler_$(PLATFORM) linked for validation"
	@# Restore OS layer for test suite
	@echo 'include "$(BOOTSTRAP_LIBC)"' > std/os.lang
	@echo ""
	@echo "┌────────────────────────────────────────────────────────────────┐"
	@echo "│ STAGE 6: VALIDATION (Test Final Binary)                        │"
	@echo "└────────────────────────────────────────────────────────────────┘"
	@# Test the FINAL platform-specific binary (what we actually promote)
	@echo "Testing final compiler_$(PLATFORM) binary..."
	COMPILER=/tmp/bootstrap_verify/compiler_$(PLATFORM) ./test/run_llvm_suite.sh
	@echo ""
	@echo "┌────────────────────────────────────────────────────────────────┐"
	@echo "│ STAGE 7: ARCHIVE + PROMOTE                                     │"
	@echo "└────────────────────────────────────────────────────────────────┘"
	@# Archive current bootstrap to GitHub release + local cache
	@OLD_COMMIT=$$(cat bootstrap/current/COMMIT 2>/dev/null || echo ""); \
	if [ "$$OLD_COMMIT" = "$(VERSION)" ] && \
	   { ! cmp -s bootstrap/current/compiler_linux.ll /tmp/bootstrap_verify/compiler_linux.ll || \
	     ! cmp -s bootstrap/current/compiler_macos.ll /tmp/bootstrap_verify/compiler_macos.ll || \
	     ! cmp -s bootstrap/current/lang_reader/source.ast /tmp/bootstrap_verify/reader_ast1.ast; }; then \
		echo "ERROR: bootstrap identity $(VERSION) already names different artifacts."; \
		echo "Commit the previously promoted root before bootstrapping more compiler changes."; \
		exit 1; \
	fi; \
	if [ -n "$$OLD_COMMIT" ] && [ "$$OLD_COMMIT" != "$(VERSION)" ]; then \
		echo "Archiving old bootstrap $$OLD_COMMIT..."; \
		if [ "$(PUBLISH_BOOTSTRAP)" = "1" ]; then \
			tar -czf /tmp/bootstrap-$$OLD_COMMIT.tar.gz -C bootstrap current/; \
			if $(GH) release view bootstrap-$$OLD_COMMIT >/dev/null 2>&1; then \
				if $(GH) release view bootstrap-$$OLD_COMMIT --json assets --jq '.assets[].name' | grep -Fxq "bootstrap-$$OLD_COMMIT.tar.gz"; then \
					echo "  GitHub release and archive already exist"; \
				else \
					echo "ERROR: GitHub release bootstrap-$$OLD_COMMIT exists without its archive."; \
					exit 1; \
				fi; \
			else \
				$(GH) release create bootstrap-$$OLD_COMMIT /tmp/bootstrap-$$OLD_COMMIT.tar.gz \
					--title "Bootstrap $$OLD_COMMIT" \
					--notes "Preserved bootstrap root $$OLD_COMMIT. COMMIT and PROVENANCE inside the archive identify and hash the root; this release tag is an artifact label." \
					--latest=false || { echo "ERROR: Failed to create GitHub release. Bootstrap aborted."; exit 1; }; \
				echo "  Created GitHub release bootstrap-$$OLD_COMMIT"; \
			fi; \
			rm -f /tmp/bootstrap-$$OLD_COMMIT.tar.gz; \
		else \
			echo "  Skipping GitHub release (PUBLISH_BOOTSTRAP=0)"; \
		fi; \
		echo "  Saving to local archive..."; \
		if [ -d bootstrap/archive/$$OLD_COMMIT ]; then \
			if diff -qr bootstrap/current bootstrap/archive/$$OLD_COMMIT >/dev/null; then \
				echo "  Matching local archive already exists"; \
			else \
				echo "ERROR: bootstrap/archive/$$OLD_COMMIT already contains different files."; \
				exit 1; \
			fi; \
		elif [ -e bootstrap/archive/$$OLD_COMMIT.tar.gz ]; then \
			echo "ERROR: bootstrap/archive/$$OLD_COMMIT.tar.gz already exists; refusing an ambiguous duplicate."; \
			exit 1; \
		else \
			mkdir bootstrap/archive/$$OLD_COMMIT; \
			cp -r bootstrap/current/* bootstrap/archive/$$OLD_COMMIT/; \
			echo "  Saved bootstrap/archive/$$OLD_COMMIT/"; \
		fi; \
		echo "  Managing local archive (target: 10 folders, 10 tarballs)..."; \
		cd bootstrap/archive && \
		remote_archive_exists() { \
			IDENTITY="$$1"; \
			[ "$(PUBLISH_BOOTSTRAP)" = "1" ] && \
			$(GH) release view "bootstrap-$$IDENTITY" --json assets --jq '.assets[].name' 2>/dev/null | \
				grep -Fxq "bootstrap-$$IDENTITY.tar.gz"; \
		}; \
		FOLDERS=$$(ls -dt */ 2>/dev/null | sed 's|/||'); \
		COMPRESS=$$(echo "$$FOLDERS" | tail -n +11 | head -10); \
		DELETE=$$(echo "$$FOLDERS" | tail -n +21); \
		for f in $$COMPRESS; do \
			if [ -d "$$f" ] && [ ! -f "$$f.tar.gz" ]; then \
				tar -czf "$$f.tar.gz" "$$f" && rm -rf "$$f" && echo "    Compressed $$f"; \
			fi; \
		done; \
		for f in $$DELETE; do \
			if remote_archive_exists "$$f"; then \
				rm -rf "$$f" "$$f.tar.gz" 2>/dev/null && echo "    Deleted $$f (verified in GitHub)"; \
			else \
				echo "    Kept $$f (matching GitHub archive not verified)"; \
			fi; \
		done; \
		OLD_TARBALLS=$$(ls -t *.tar.gz 2>/dev/null | tail -n +11); \
		for t in $$OLD_TARBALLS; do \
			IDENTITY=$${t%.tar.gz}; \
			if remote_archive_exists "$$IDENTITY"; then \
				rm -f "$$t" && echo "    Deleted $$t (verified in GitHub)"; \
			else \
				echo "    Kept $$t (matching GitHub archive not verified)"; \
			fi; \
		done; \
	fi
	@# Stage complete files beside the current root, then move the identity marker
	@# last. An interruption cannot leave a truncated artifact claiming success.
	@mkdir -p bootstrap/current/lang_reader
	cp /tmp/bootstrap_verify/compiler_linux.ll bootstrap/current/.compiler_linux.ll.next
	cp /tmp/bootstrap_verify/compiler_macos.ll bootstrap/current/.compiler_macos.ll.next
	cp /tmp/bootstrap_verify/reader_ast1.ast bootstrap/current/lang_reader/.source.ast.next
	@echo "$(VERSION)" > bootstrap/current/.COMMIT.next
	@echo "compiler_linux.ll:" > bootstrap/current/.PROVENANCE.next
	@echo "  sha256: $$(shasum -a 256 bootstrap/current/.compiler_linux.ll.next | cut -d' ' -f1)" >> bootstrap/current/.PROVENANCE.next
	@echo "compiler_macos.ll:" >> bootstrap/current/.PROVENANCE.next
	@echo "  sha256: $$(shasum -a 256 bootstrap/current/.compiler_macos.ll.next | cut -d' ' -f1)" >> bootstrap/current/.PROVENANCE.next
	@echo "built_by: $(VERSION)" >> bootstrap/current/.PROVENANCE.next
	@echo "bootstrap_from: $(BOOTSTRAP_FROM)" >> bootstrap/current/.PROVENANCE.next
	@echo "built_at: $$(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> bootstrap/current/.PROVENANCE.next
	@echo "source_commit: $(VERSION)" >> bootstrap/current/.PROVENANCE.next
	@echo "verification:" >> bootstrap/current/.PROVENANCE.next
	@echo "  llvm_fixed_point: true (kernel2.ll === kernel3.ll)" >> bootstrap/current/.PROVENANCE.next
	@echo "  ast_fixed_point: true (reader_ast1 === reader_ast2)" >> bootstrap/current/.PROVENANCE.next
	@echo "  cross_target_objects: true (linux x86_64 and macos arm64)" >> bootstrap/current/.PROVENANCE.next
	@echo "  native_link: true (compiler_$(PLATFORM))" >> bootstrap/current/.PROVENANCE.next
	@echo "  test_suite: true (ran on compiler_$(PLATFORM) binary)" >> bootstrap/current/.PROVENANCE.next
	@echo "lang_reader/source.ast:" >> bootstrap/current/.PROVENANCE.next
	@echo "  sha256: $$(shasum -a 256 bootstrap/current/lang_reader/.source.ast.next | cut -d' ' -f1)" >> bootstrap/current/.PROVENANCE.next
	@echo "  lines: $$(wc -l < bootstrap/current/lang_reader/.source.ast.next)" >> bootstrap/current/.PROVENANCE.next
	@# Stage the stable install before changing the root, too.
	cp /tmp/bootstrap_verify/compiler_$(PLATFORM) out/.lang.next
	cp /tmp/bootstrap_verify/compiler_$(PLATFORM).ll out/.lang_$(VERSION).ll.next
	mv bootstrap/current/.compiler_linux.ll.next bootstrap/current/compiler_linux.ll
	mv bootstrap/current/.compiler_macos.ll.next bootstrap/current/compiler_macos.ll
	mv bootstrap/current/lang_reader/.source.ast.next bootstrap/current/lang_reader/source.ast
	mv bootstrap/current/.PROVENANCE.next bootstrap/current/PROVENANCE
	mv bootstrap/current/.COMMIT.next bootstrap/current/COMMIT
	@# Install only after archive + bootstrap promotion succeed. A release or
	@# archive failure must not replace the user's stable compiler.
	mv out/.lang_$(VERSION).ll.next out/lang_$(VERSION).ll
	mv out/.lang.next out/lang
	@echo "Installed: out/lang (from compiler_$(PLATFORM))"
	@rm -rf /tmp/bootstrap_verify
	@echo ""
	@echo "╔════════════════════════════════════════════════════════════════╗"
	@echo "║                    BOOTSTRAP COMPLETE                          ║"
	@echo "╠════════════════════════════════════════════════════════════════╣"
	@echo "║ Verified:                                                      ║"
	@echo "║   ✓ LLVM fixed point (kernel2.ll === kernel3.ll)               ║"
	@echo "║   ✓ AST fixed point (reader_ast1 === reader_ast2)              ║"
	@echo "║   ✓ Both .ll files cross-target checked                       ║"
	@echo "║   ✓ Test suite on final binary (compiler_$(PLATFORM))          ║"
	@echo "║                                                                ║"
	@echo "║ Installed: out/lang = compiler_$(PLATFORM) (tested)            ║"
	@echo "║                                                                ║"
	@echo "║ Promoted: bootstrap/current/ ($(VERSION))                     ║"
	@echo "║   - compiler_linux.ll (clang-verified)                         ║"
	@echo "║   - compiler_macos.ll (clang-verified, tested on macos)        ║"
	@echo "║   - lang_reader/source.ast                                     ║"
	@echo "╚════════════════════════════════════════════════════════════════╝"
	@echo ""
	@echo "Rebuild out/lang: clang -O2 bootstrap/current/compiler_$(PLATFORM).ll -o out/lang"

# Same verified promotion pipeline, without exporting the old archive to GitHub.
bootstrap-local:
	@$(MAKE) bootstrap PUBLISH_BOOTSTRAP=0

# Diagnostic fixed-point check only. Promotion always uses bootstrap above.
bootstrap-verify: LANGBE=llvm
bootstrap-verify: generate-os-layer generate-version-info
	@rm -rf /tmp/bootstrap_verify
	@mkdir -p out out/ast /tmp/bootstrap_verify
	@if [ ! -f $(BOOTSTRAP_LL) ]; then echo "ERROR: $(BOOTSTRAP_LL) not found"; exit 1; fi
	clang -O2 $(BOOTSTRAP_LL) -o /tmp/bootstrap_verify/ctrusted
	@echo 'include "$(BOOTSTRAP_LIBC)"' > std/os.lang
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/bootstrap_verify/ctrusted std/core.lang out/version_info.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/kernel1.ll
	clang -O2 /tmp/bootstrap_verify/kernel1.ll -o /tmp/bootstrap_verify/kernel1
	/tmp/bootstrap_verify/kernel1 src/lang_reader.lang --emit-expanded-ast -o /tmp/bootstrap_verify/reader_ast1.ast
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/bootstrap_verify/kernel1 std/core.lang out/version_info.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/kernel2.ll
	clang -O2 /tmp/bootstrap_verify/kernel2.ll -o /tmp/bootstrap_verify/kernel2
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/bootstrap_verify/kernel2 std/core.lang out/version_info.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang src/sexpr_reader.lang src/main.lang -o /tmp/bootstrap_verify/kernel3.ll
	@if ! diff -q /tmp/bootstrap_verify/kernel2.ll /tmp/bootstrap_verify/kernel3.ll > /dev/null; then \
		echo "LLVM FIXED POINT FAILED"; exit 1; \
	fi
	/tmp/bootstrap_verify/kernel2 src/lang_reader.lang --emit-expanded-ast -o /tmp/bootstrap_verify/reader_ast2.ast
	@if ! diff -q /tmp/bootstrap_verify/reader_ast1.ast /tmp/bootstrap_verify/reader_ast2.ast > /dev/null; then \
		echo "AST FIXED POINT FAILED"; exit 1; \
	fi
	COMPILER=/tmp/bootstrap_verify/kernel2 ./test/run_llvm_suite.sh

# Compatibility alias for the old Mac-only verifier. The historical recipe
# overwrote out/lang before its fixed-point comparison and tests completed.
llvm-verify:
	@echo "llvm-verify is deprecated; running the non-promoting verifier."
	@$(MAKE) bootstrap-verify

# Release preparation: verify/promote, then tell the author how to record it.
release:
	@if [ -z "$(TAG)" ]; then \
		echo "Usage: make release TAG=v0.2.0"; \
		exit 1; \
	fi
	@$(MAKE) bootstrap
	@echo "Bootstrap root $(VERSION) is verified in bootstrap/current/."
	@echo "Commit the release state, then run: git tag $(TAG)"

# Run the test suite
test-suite:
	@if [ ! -x $(LANG) ]; then $(MAKE) init; fi
	@./test/run_llvm_suite.sh

# Run ALL tests
test-all: test-suite
	@./test/run_wasm_suite.sh
	@./test/run_direct_wasm.sh
	@./test/run_compiler_wasm.sh

test-compiler-wasm:
	@./test/run_compiler_wasm.sh

test-direct-wasm:
	@./test/run_direct_wasm.sh

# Compile and run sample test programs
test-run:
	@if [ ! -x $(LANG) ]; then $(MAKE) init; fi
	@echo "=== hello.lang ==="
	@LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) run test/suite/181_hello.lang
	@echo "=== factorial.lang ==="
	@LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) run test/suite/174_factorial.lang

# Compile a .lang file (usage: make compile FILE=test/hello.lang)
compile:
	@if [ ! -x $(LANG) ]; then $(MAKE) init; fi
	LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) $(FILE) -o out/$(notdir $(basename $(FILE))).ll

# Full build chain for a .lang file (usage: make run FILE=test/hello.lang)
run:
	@if [ ! -x $(LANG) ]; then $(MAKE) init; fi
	LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) run $(FILE)

# Build with stdlib (usage: make stdlib-run FILE=myprogram.lang)
stdlib-run:
	@if [ ! -x $(LANG) ]; then $(MAKE) init; fi
	LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) run std/core.lang $(FILE)

# Run with development compiler (usage: make dev-run FILE=test/suite/188_effect_exception.lang)
dev-run:
	@if [ ! -x $(LANG_NEXT) ]; then echo "Run 'make build' first"; exit 1; fi
	@LANGBE=llvm LANGOS=$(PLATFORM) $(LANG_NEXT) run $(FILE); STATUS=$$?; echo "Exit: $$STATUS"

# Run with dev compiler + stdlib (usage: make dev-stdlib-run FILE=myprogram.lang)
dev-stdlib-run:
	@if [ ! -x $(LANG_NEXT) ]; then echo "Run 'make build' first"; exit 1; fi
	@LANGBE=llvm LANGOS=$(PLATFORM) $(LANG_NEXT) run std/core.lang $(FILE); STATUS=$$?; echo "Exit: $$STATUS"

# Clean: remove non-essential build artifacts
clean:
	rm -f out/*.s out/*.o out/verify.s
	rm -f out/hello out/factorial
	rm -f $(LANG_NEXT)

# Distclean: remove everything in out/
distclean:
	rm -rf out/*

# Show current state
status:
	@echo "Bootstrap root: $(BOOTSTRAP_FROM)"
	@echo "Current commit: $(VERSION)"
	@if [ -x $(LANG) ]; then \
		if [ -L $(LANG) ]; then echo "lang -> $$(readlink $(LANG))"; else echo "lang: executable"; fi; \
	else \
		echo "lang: not set (run 'make bootstrap')"; \
	fi
	@if [ -L $(LANG_NEXT) ]; then \
		echo "lang_next -> $$(readlink $(LANG_NEXT))"; \
	fi

# ============================================================
# SPLIT ARCHITECTURE: kernel + lang_reader
# ============================================================
#
# The compiler is split into:
#   kernel = AST -> target code (codegen + sexpr_reader)
#   lang_reader = lang -> AST (lexer + parser + ast_emit)
#
# Composition: kernel -c lang_reader.ast = full lang compiler

# Kernel core (for composition - no main)
# Note: parser.lang needed for AST node accessors used by codegen and sexpr_reader
# Note: limits.lang is included by std/core.lang, don't list explicitly
KERNEL_CORE := std/core.lang src/lexer.lang src/parser.lang src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/sexpr_reader.lang

# Kernel binary sources (core + main for standalone kernel)
KERNEL_SOURCES := $(KERNEL_CORE) src/kernel_main.lang

# Lang reader sources (includes lexer/parser/ast_emit + the reader definition)
# Note: limits.lang is included by std/core.lang, don't list explicitly
LANG_READER_SOURCES := std/core.lang src/lexer.lang src/parser.lang src/ast_emit.lang src/lang_reader.lang

# Compiler entry point (uses reader_transform from reader + generate from kernel)
COMPILER_SOURCES := src/compiler.lang

# Build kernel binary (AST -> x86)
build-kernel:
	@if [ ! -x $(LANG) ]; then $(MAKE) init; fi
	@mkdir -p out
	LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) $(KERNEL_SOURCES) -o out/kernel.ll
	clang -O2 out/kernel.ll -o out/kernel
	@echo "Built: out/kernel"

# Build lang_reader binary (standalone tool: lang -> AST to stdout)
build-lang-reader:
	@if [ ! -x $(LANG) ]; then $(MAKE) init; fi
	@mkdir -p out
	LANGBE=llvm LANGOS=$(PLATFORM) $(LANG) $(LANG_READER_SOURCES) src/reader_main.lang -o out/lang_reader.ll
	clang -O2 out/lang_reader.ll -o out/lang_reader
	@echo "Built: out/lang_reader"

# Emit kernel core AST (for composition - no main)
# Note: requires lang_next which has --emit-ast support
emit-kernel-ast: build
	@mkdir -p out/ast
	$(LANG_NEXT) $(KERNEL_CORE) --emit-ast -o out/ast/kernel.ast
	@echo "Wrote: out/ast/kernel.ast"

# Emit lang_reader AST (for composition - just the reader, deps come from kernel)
emit-lang-reader-ast: build
	@mkdir -p out/ast
	$(LANG_NEXT) src/lang_reader.lang --emit-ast -o out/ast/lang_reader.ast
	@echo "Wrote: out/ast/lang_reader.ast"

# Emit compiler AST (for composition)
emit-compiler-ast: build
	@mkdir -p out/ast
	$(LANG_NEXT) $(COMPILER_SOURCES) --emit-ast -o out/ast/compiler.ast
	@echo "Wrote: out/ast/compiler.ast"

# Seed the bootstrap directory with initial AST files
seed-bootstrap: emit-kernel-ast emit-lang-reader-ast emit-compiler-ast
	@mkdir -p bootstrap/$(GIT_COMMIT)/kernel bootstrap/$(GIT_COMMIT)/lang_reader bootstrap/$(GIT_COMMIT)/compiler
	cp out/ast/kernel.ast bootstrap/$(GIT_COMMIT)/kernel/source.ast
	cp out/ast/lang_reader.ast bootstrap/$(GIT_COMMIT)/lang_reader/source.ast
	cp out/ast/compiler.ast bootstrap/$(GIT_COMMIT)/compiler/source.ast
	@echo "Seeded: bootstrap/$(GIT_COMMIT)/"
	@echo "To activate: ln -sfn $(GIT_COMMIT) bootstrap/current"

# Test composition: kernel + reader via -r mode
# This is the new composition flow:
#   1. Build kernel AST with --emit-exe-ast (standalone, with ___main)
#   2. Build kernel binary with --embed-self (self-aware, carries its own AST)
#   3. Build reader AST with --emit-expanded-ast (for composition, NO ___main)
#   4. Compose: kernel -r lang reader.ast -> lang1
#   5. Test: lang1 can compile programs that require "std/core"
test-composition:
	@echo "╔════════════════════════════════════════════════════════════════╗"
	@echo "║              TEST COMPOSITION (LLVM)                           ║"
	@echo "╚════════════════════════════════════════════════════════════════╝"
	@mkdir -p /tmp/compose_test
	@echo ""
	@echo "┌─ Step 1: Build kernel AST (--emit-exe-ast, with ___main) ──────┐"
	LANGBE=llvm LANGOS=$(PLATFORM) ./out/lang --emit-exe-ast \
		std/core.lang out/version_info.lang src/lexer.lang src/parser.lang \
		src/codegen.lang src/codegen_llvm.lang src/codegen_wasm.lang src/ast_emit.lang \
		src/sexpr_reader.lang src/main.lang \
		-o /tmp/compose_test/kernel.ast
	@echo "  Kernel AST: $$(wc -l < /tmp/compose_test/kernel.ast) lines"
	@echo ""
	@echo "┌─ Step 2: Build kernel binary (--embed-self) ───────────────────┐"
	LANGBE=llvm LANGOS=$(PLATFORM) ./out/lang /tmp/compose_test/kernel.ast \
		--embed-self -o /tmp/compose_test/kernel.ll
	clang -O2 /tmp/compose_test/kernel.ll -o /tmp/compose_test/kernel
	@echo "  Built: /tmp/compose_test/kernel"
	/tmp/compose_test/kernel version || true
	@echo ""
	@echo "┌─ Step 3: Build reader AST (--emit-expanded-ast, NO ___main) ───┐"
	./out/lang --emit-expanded-ast src/lang_reader.lang \
		-o /tmp/compose_test/lang_reader.ast
	@echo "  Reader AST: $$(wc -l < /tmp/compose_test/lang_reader.ast) lines"
	@echo ""
	@echo "┌─ Step 4: Compose kernel + reader (-r lang) ────────────────────┐"
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/compose_test/kernel -r lang /tmp/compose_test/lang_reader.ast \
		-o /tmp/compose_test/lang1.ll
	clang -O2 /tmp/compose_test/lang1.ll -o /tmp/compose_test/lang1
	@echo "  Built: /tmp/compose_test/lang1"
	/tmp/compose_test/lang1 version || true
	@echo ""
	@echo "┌─ Step 5: Test composed compiler ───────────────────────────────┐"
	@echo 'require "std/core"' > /tmp/compose_test/hello.lang
	@echo 'func main() i64 { println("Hello from composed compiler!"); return 0; }' >> /tmp/compose_test/hello.lang
	LANGBE=llvm LANGOS=$(PLATFORM) /tmp/compose_test/lang1 /tmp/compose_test/hello.lang -o /tmp/compose_test/hello.ll
	clang /tmp/compose_test/hello.ll -o /tmp/compose_test/hello
	@/tmp/compose_test/hello
	@echo ""
	@echo "╔════════════════════════════════════════════════════════════════╗"
	@echo "║              COMPOSITION TEST PASSED                           ║"
	@echo "╚════════════════════════════════════════════════════════════════╝"

# Test bootstrap: verify true fixed point
# The fixed point is: A -c lang.lang === B -c lang.lang
# where A = {kernel -c lang.ast} -c lang.lang
# NOT: {kernel -c lang.ast} === A (AST-built vs source-built may differ)
test-bootstrap:
	@echo "test-bootstrap is deprecated; running the non-promoting verifier."
	@$(MAKE) bootstrap-verify
